#pragma once

enum eItemCollision {
    ITEMCOLLISION_NONE,
    ITEMCOLLISION_NORMAL,
    ITEMCOLLISION_PLATFORM,
    ITEMCOLLISION_GATEWAY,
    ITEMCOLLISION_SWITCHEROO,
    ITEMCOLLISION_ONE_WAY_LEFT_RIGHT,
    ITEMCOLLISION_VIP_GATEWAY,
    ITEMCOLLISION_WATERFALL,
    ITEMCOLLISION_ADVENTURE_DOOR,
    ITEMCOLLISION_GORILLA,
    ITEMCOLLISION_TEAMENTRANCE,
    ITEMCOLLISION_GUILDENTRANCE,
    ITEMCOLLISION_CLOUD,
};